// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVixtjsNQShQHfWOLLvKXo-WFbNCvAqSc',
    appId: '1:612146326631:web:40514b4f5cadf0e641b8c2',
    messagingSenderId: '612146326631',
    projectId: 'first-97043',
    authDomain: 'first-97043.firebaseapp.com',
    storageBucket: 'first-97043.firebasestorage.app',
    measurementId: 'G-9FBLZFCZJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUd-gH6MVVXghzZxVJg-yBjv1Ify1gZ3s',
    appId: '1:612146326631:android:e5f87a5850bff9bc41b8c2',
    messagingSenderId: '612146326631',
    projectId: 'first-97043',
    storageBucket: 'first-97043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM3XxIlMUatqGjtNFMG7CEzTJvOqiE3UY',
    appId: '1:612146326631:ios:79a86b856a6b265041b8c2',
    messagingSenderId: '612146326631',
    projectId: 'first-97043',
    storageBucket: 'first-97043.firebasestorage.app',
    iosBundleId: 'com.example.barabar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM3XxIlMUatqGjtNFMG7CEzTJvOqiE3UY',
    appId: '1:612146326631:ios:79a86b856a6b265041b8c2',
    messagingSenderId: '612146326631',
    projectId: 'first-97043',
    storageBucket: 'first-97043.firebasestorage.app',
    iosBundleId: 'com.example.barabar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVixtjsNQShQHfWOLLvKXo-WFbNCvAqSc',
    appId: '1:612146326631:web:6cc552fa21bce73441b8c2',
    messagingSenderId: '612146326631',
    projectId: 'first-97043',
    authDomain: 'first-97043.firebaseapp.com',
    storageBucket: 'first-97043.firebasestorage.app',
    measurementId: 'G-HJMD4WPYVB',
  );
}
